### PR TITLE
Add isModal config on FastAuthWallet

### PR DESCRIPTION
**Pull request by Pessina**
#Summary

This PR introduces an option for the caller to choose whether the wallet should be rendered inside a modal or not, making it easier to customize the UI.

## Usage

Render the wallet in a modal (default behavior):

```
setupFastAuthWallet({
  relayerUrl,
  walletUrl: 'http://localhost:3000',
});
```

Render the wallet without a modal:

```
setupFastAuthWallet({
  relayerUrl,
  walletUrl: 'http://localhost:3000',
  isModal: false,
});
```

### CODE REVIEW

**Comment by charlesmooredev** [comment]
Hey, any updates on the ETA?

**Comment by Pessina** [comment]
@charlesmooredev sorry, it took more time than expected to use Shadcn for the UI. 

But I asked @esaminu for review it again

**Review by esaminu — DISMISSED** [review]
LGTM

**Review by esaminu — APPROVED** [review]
LGTM

**Pull request merged**
