### PR TITLE
Replace Native dialog with Modal/Drawer

### PR DESCRIPTION
**Pull request by benmalcom**
- This PR replaces the native dialog currently being used to transactions in `fast-auth-wallet` with a more polished  modal for desktop and drawer for mobile.
- It also enables the switch from page-based authentication in `near-discovery` to modal/drawer based authentication.

Screenshot 2024-01-17 at 2 15 13 PM
Screenshot 2024-01-17 at 2 15 28 PM
Screenshot 2024-01-17 at 2 20 07 PM
Screenshot 2024-01-17 at 3 07 06 PM
Screenshot 2024-01-17 at 3 33 42 PM
Screenshot 2024-01-17 at 3 33 56 PM

### CODE REVIEW

**Comment by DavidM-D** [comment]
Those screenshots are looking really good!

**Comment by DavidM-D** [comment]
How far out is this from being merged?

**Comment by benmalcom** [comment]
@esaminu any final checks?

**Review by esaminu — APPROVED** [review]
LGTM

**Pull request merged**
